### PR TITLE
add sqlite3 support

### PR DESCRIPTION
**Pull request by unreal**
I was just kicking the tires a bit with utron and didn't have a mysql or postgres environment to play around in, so I hacked in GORM's sqlite3 support.

I could be (probably) missing something here, but I figured it wouldn't hurt.

### CODE REVIEW

**Comment by Slacki** [comment]
+1

**Comment by gernest** [comment]
@unreal awesome.

Something to note here, the import `github.com/jinzhu/gorm/dialects/sqlite` just imports the necessary sqlite3 driver `github.com/mattn/go-sqlite3` which relies on CGO.

Previously I was skeptic of adding a dependency that relies in CGO, but now I think it is about time I accept reality.

Thanks for this, I haven't poked gorm for a while and sure missed their dialects. I found mssql too to we can use them to support about four databases.

I am now thinking it will also make sense replacing the normal driver imports in `models.go` with gorm dialects.

**Comment by unreal** [comment]
@gernest great, thanks! 

To be honest I didn't look under the hood of GORM's dialect support... didn't realize it was just a convenience. Does it make more sense for utron to handle things similarly? e.g. directing the user to import the appropriate db driver in their models or an utron convenience import. It seems unnecessary to import several db drivers by default.

**Comment by gernest** [comment]
@unreal  well that is what I thought at first, but most of people using utron wants everything to work out of the box. And letting it being handled by gorm reduces maintanance headache. I think usind gorm dialects for postgres, mysql and mssql will good too.

And probably after that update the README to point that mssql is supported too.

On performance point, well that was not the goal of   utron, but maybe we will need benchmarks for that.

**Comment by Slacki** [comment]
After this PR Windows users must have gcc compiler installed.

**Comment by gernest** [comment]
@Slacki well that is bad news.

**Comment by gernest** [comment]
Bad news. @Slacki do you have any suggestion on this?

**Comment by Slacki** [comment]
@gernest yeah, it's a pain in the ass a little bit. Don't have any suggestions, unfortunally.

**Comment by Slacki** [comment]
So guys I must admit I was happy about this PR but installing gcc on Windows is a huge dependency and might be scaring. 

I think the one should include the dialect he/she wants. 

As for now I'd delete this include with sqlite.

**Comment by gernest** [comment]
@Slacki so be it. I am removing this for now. But have you checked the case for mssql too? I mean I added `myssql` driver too.

**Comment by Slacki** [comment]
Nope I just installed newest version of utron. But I guess its problem with sqlite driver only.

**Comment by Slacki** [comment]
Everything was on the fly. I am on the phone right now and can't really test it.

**Comment by unreal** [comment]
I knew I was probably missing something ;)

Personally I like GORM's approach to offering some easy includes for recommended drivers. I suppose another option would be to add generators to utron (e.g. `utron g model foo`) that includes an appropriate driver based on the database type in the config file.

**Comment by gernest** [comment]
@unreal I never thought about generators( seems they can be useful in this case). Maybe we can remove the sqlite driver and add information on the readme If someone wants to use it they should include the driver.

As the rest seems to be okay.

**Comment by Slacki** [comment]
@gernest Yup, good idea.

**Pull request merged**
